server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zyk116201
    url: jdbc:mysql://localhost:3306/yioi?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yioi.Mapper
  tomcat:
    max-http-form-post-size: -1
